### ISSUE TITLE
Customize variables

### ISSUE THREAD

**Issue by krystian50** [jmaczan/bulma-helpers#1]
I think it would be nice to import `bulma-helpers` as:
```javascript
import "src/styles/bulma-helpers-settings.sass";
import "bulma-helpers/bulma-helpers.sass";
```
If you import the lib as sass file, you can override default variables in your own settings file, such as:
File: ../borders.sass
$range-start: 1
$range-end: 10
$interval: 1

You can do it by `!default` flag, example:
https://github.com/uswds/uswds#customization-and-theming
solution:
https://github.com/uswds/uswds/blob/c98f69c879d0fc9e2e2cc72ee9ee9743c1971d39/src/stylesheets/core/_variables.scss

I can do it for you, if you want to.
I feel like main case to use this library is by copying that to your own styles structure. If you want to keep it more as a pure npm plugin and a part of vendor, I think customizing that from the outside would be a nice approach.

**Comment by jmaczan** [comment]
That's a good point, I will rebuild the lib to comply your remarks about customization. 🙂
