### ISSUE TITLE
Question about ranges customization

### ISSUE THREAD

**Issue by wanxe** [jmaczan/bulma-helpers#11]
Hey! good work with the helpers, they are really useful :)

I'm building a new Nuxt project, and I'm trying to customize the range intervals but nothing happens.

There is the code that I've already on my main.scss.

```
@import "~bulma-helpers/bulma-helpers.sass";
$sizing-range-start: 1 !default;
$sizing-range-end: 8 !default;
$sizing-interval: 8 !default;
```

Thanks

**Comment by jmaczan** [comment]
Hello Jorge,

Try to set the variables before importing Bulma-helpers. :)

Greetings,
Jędrzej

**Comment by wanxe** [comment]
I have tried and the result is exactly the same, the interval is still 5 instead 8.

**Comment by jmaczan** [comment]
Hi Jorge,

Honestly at the moment I have no idea why does it happen. I'm very busy in my private life, so I'm sorry about not being able to resolve your problem. If you find out solution, feel free to share it or contribute to the Bulma Helpers.

**Comment by jmaczan** [comment]
Hi @wanxe,

Today I finally found some time to solve your problem 😄 First of all - variables for customizing margin and padding are
```
$spacing-range-start: 5 !default
$spacing-range-end: 150 !default
$spacing-interval: 5 !default
```

Secondly, to effectively customize variables follow this instruction:
1. install `node-sass` (`npm install node-sass --save-dev`)
2. create script for compiliting `scss` to `css` (i.e. `"customize-css": "node-sass --omit-source-map-url ./src/scss/BulmaHelpers.scss ./src/css/BulmaHelpers.css"`)
3. create folder (i.e. called `scss`) and some `.scss` file in which you will customize `bulma-helpers` variables (i.e. `scss/bulma-helpers-customization.scss`)
4. define variables which you want to override before `bulma-helpers` import

example content of the file:
```
@charset "utf-8";
$sizing-range-start: 1;
$sizing-range-end: 666;
$sizing-interval: 6;
@import "../../node_modules/bulma-helpers/bulma-helpers.sass";
```

5. run compiling script to build new `css` file (i.e. `npm run customize-css`
6. import result file in one of your scss files, i.e. `@import "css/BulmaHelpers.css";`

I'll describe this process in docs. 😃

**Comment by jmaczan** [comment]
I close the issue as there are no more comments here
