### ISSUE TITLE
Feature Request: Negative Value

### ISSUE THREAD

**Issue by runyasak** [jmaczan/bulma-helpers#12]
Hi, your project is very awesome. I always use it with project that using bulma, so I don't need to create atomic CSS classes.

However, my new project design need using negative margin for some tag. I would like to have it in this helpers.

Is it interesting or useful? Please, let me know your ideas and comments.

Thank you,
World

**Comment by jmaczan** [comment]
Hi Runyasak,

Have you tried to customize range of classes on your own? You can set values of $range-start and $range-end for each helper and generate new classes.

Best,
Jędrzej

**Comment by jmaczan** [comment]
I close the issue as there are no more comments here
