### ISSUE TITLE
Feature Request: x & y-axis modifiers similar to Bootstrap's px-5 & my-5

### ISSUE THREAD

**Issue by caffeinatedMike** [jmaczan/bulma-helpers#13]
I've been waiting for someone to create a helper library for Bulma, so thank you for finally doing so! 

Would it be possible to add the x & y axis helpers (Such as [Bootstrap's mx-5 & py-5](https://getbootstrap.com/docs/4.0/utilities/spacing/#examples)), so we can avoid having to do separate classes for left & right, top & bottom?

**Comment by joshbmarshall** [comment]
To make it more understandable in line with the other classes in this module I'd suggest you use the words horizontal and vertical e.g. has-padding-vertical-5

**Comment by jmaczan** [comment]
Hello,

Feel free to contribute with your changes. It's more than welcome :)

Best,
Jędrzej

**Comment by zelenyjan** [comment]
This is now part of Bulma https://bulma.io/documentation/helpers/spacing-helpers/
