### ISSUE TITLE
Add package to https://cdnjs.com/libraries/

### ISSUE THREAD

**Issue by terabytesoftw** [jmaczan/bulma-helpers#24]
It would be possible to add this repository to cdnjs, it would be great to have a cdn, 

thanks for your great work.

**Comment by jmaczan** [comment]
Hi, I send request for it. Link: https://github.com/cdnjs/packages/issues/687

**Comment by jmaczan** [comment]
Added.

https://cdnjs.com/libraries/bulma-helpers
