### ISSUE TITLE
Licence

### ISSUE THREAD

**Issue by baselakasha** [jmaczan/bulma-helpers#32]
Hello,

This is a very useful project and it makes bulma usable. It would be helpful if a licence is included so it can be used without legal issues.

Thanks

Basel.

**Comment by jmaczan** [comment]
Hi Basel,

Here you go: https://github.com/jmaczan/bulma-helpers/blob/master/LICENSE.md :slightly_smiling_face: 

Best regards,
Jędrzej

**Comment by baselakasha** [comment]
> Hi Basel,
> 
> Here you go: https://github.com/jmaczan/bulma-helpers/blob/master/LICENSE.md 🙂
> 
> Best regards, Jędrzej

Perfect thanks.
