### ISSUE TITLE
Making the flex classes responsive

### ISSUE THREAD

**Issue by mayowa** [jmaczan/bulma-helpers#4]
Hi thank you for this!
Can you support Bulma's media query class suffixes on the flex helpers? I think it would be a great addition

e.g
justify-content-tablet 
justify-flex-end-mobile

Thank you

**Comment by mayowa** [comment]
Hi jmaczan,
Thanks!

**Comment by jmaczan** [comment]
Hi @mayowa,
I added module with responsive flex classes. :slightly_smiling_face: You can find it in version 0.3.3. 
I hope you will enjoy it!

**Comment by jmaczan** [comment]
@mayowa no problem, let me know if you will have more ideas how to improve the library. also, feel free to pull request :slightly_smiling_face:
