### ISSUE TITLE
Wrong syntax on justify-end

### ISSUE THREAD

**Issue by codev0** [jmaczan/bulma-helpers#8]
Hello,

`justify-end` class has wrong `justify-content` css syntax,
Now
```
.justify-end {
  justify-content: end !important;
}
```
Have to
```
.justify-end {
  justify-content: flex-end !important;
}
```

![image](https://user-images.githubusercontent.com/910573/57127227-8173ce00-6db1-11e9-875b-1e1e87004957.png)

**Comment by jmaczan** [comment]
Hi Airat,

According to https://developer.mozilla.org/en-US/docs/Web/CSS/justify-content, `justify-content: end` is valid CSS property. :slightly_smiling_face: It's not as popular as `flex-end`, but it's possible that some people are already using `justify-content: end`. I don't want to break their code with such change and keep `end` in codebase, so I close the issue.

Thank you for your contribution and feel free to report another issues! :slightly_smiling_face: 

Jędrzej

**Comment by codev0** [comment]
Whoops, sorry, first I had to look at the spec.

Thanks for being kind.

Could you show an example how to get `justify-content: flex-end`?

**Comment by jmaczan** [comment]
Hello again,

You should use class `justify-flex-end`. :slightly_smiling_face: 

Best,
Jędrzej
